### ISSUE TITLE
Hi, how to test it?

### ISSUE THREAD

**Issue by dahaibao** [YuboLong/MyLive#1]
Hi 兄弟， 对你些的东西很感兴趣，这个实时推流直播要如何测试，能有一个推流的测试类吗？ 请赐教。

**Comment by Kevin-Mui** [comment]
我也想测试怎么玩的，兄弟求指教

**Comment by YuboLong** [comment]
按照README上面的方法操作就行了

**Comment by dahaibao** [comment]
这个播放flv是不是很卡啊

**Comment by dahaibao** [comment]
存文件没有后缀名吗？

**Comment by YuboLong** [comment]
> 这个播放flv是不是很卡啊

OBS客户端推的流上个版本没有兼容，http-flv播放会卡顿，目前master分支的代码已经修复该问题。
