### ISSUE TITLE
延迟比较高

### ISSUE THREAD

**Issue by veir-panda** [YuboLong/MyLive#2]
首先，非常感谢作者开源的项目，给了我很大的启发。

在这里，想向作者请教一个问题：

我使用OBS推流，然后VLC播放推上去的流，对比测试了MyLive与[nginx-http-flv-module](https://github.com/winshining/nginx-http-flv-module)、[pingos](https://github.com/pingostack/pingos)，发现MyLive的延迟比较高，约在10s以上，而nginx-http-flv-module和pingos在没有开启GOP缓存的模式下延迟约3s，开启后约5秒

请问作者知道这个吗，要降低这个延迟的话，有什么思路吗？

**Comment by veir-panda** [comment]
使用flv.js测试发现MyLive的延迟在了3s左右，跟VLC播放器差距比较明显，这是什么原因呢

**Comment by YuboLong** [comment]
MyLive默认开启GOP，OBS里面请降低关键帧间隔时间。理论上单机测试只有GOP的延迟。

**Comment by veir-panda** [comment]
我把关键帧间隔改成2秒之后，VLC延迟还是没变，一直在10s左右

**Comment by YuboLong** [comment]
> 我把关键帧间隔改成2秒之后，VLC延迟还是没变，一直在10s左右

我这边测试OBS的推流里面加上X264的GOP的参数，HTTP-FLV延迟大约在3秒左右。
--keyint 30

**Comment by veir-panda** [comment]
延迟10s应该是VLC播放器的问题。

我用ffplay的nobuffer模式播放延迟1秒，potplayer播放延迟在3s左右。

但是，在OBS的相同推流参数下，并且同样使用VLC播放器播放，nginx-http-flv-module和pingos的VLC播放延迟都不超过5s，这一点我实在没想通……

**Comment by YuboLong** [comment]
> 我把关键帧间隔改成2秒之后，VLC延迟还是没变，一直在10s左右



> 延迟10s应该是VLC播放器的问题。
> 
> 我用ffplay的nobuffer模式播放延迟1秒，potplayer播放延迟在3s左右。
> 
> 但是，在OBS的相同推流参数下，并且同样使用VLC播放器播放，nginx-http-flv-module和pingos的VLC播放延迟都不超过5s，这一点我实在没想通……

MYLIVE只buffer了I帧和之后的帧，下一个I帧来的时候会清除掉之前的I帧，其他实现可能buffer了好几组GOP，具体他们的实现我不太清楚

**Comment by veir-panda** [comment]
嗯嗯，谢谢你的解答~
